package com.swarnava.ghostrider.enume;

public enum VehicleType {
    BATTERY_POWERED_LICENSED_BIKE, BATTERY_POWERED_NON_LICENSED_BIKE, OIL_POWERED_BIKE, GAS_POWERED_BIKE,
    BATTERY_POWERED_LICENSED_SCOOTY, BATTERY_POWERED_NON_LICENSED_SCOOTY, OIL_POWERED_SCOOTY, GAS_POWERED_SCOOTY,
    BATTERY_POWERED_LICENSED_SCOOTER, BATTERY_POWERED_NON_LICENSED_SCOOTER, OIL_POWERED_SCOOTER, GAS_POWERED_SCOOTER,
    BATTERY_POWERED_LICENSED_AUTO, BATTERY_POWERED_NON_LICENSED_AUTO, OIL_POWERED_AUTO, GAS_POWERED_AUTO,
    CAR_2_D, CAR_3_D, CAR_4_D, CAR_5_D, CAR_6_D, CAR_7_D, CAR_8_D, CAR_9_D,
    CAR_2_P, CAR_3_P, CAR_4_P, CAR_5_P, CAR_6_P, CAR_7_P, CAR_8_P, CAR_9_P,
    CAR_2_B, CAR_3_B, CAR_4_B, CAR_5_B, CAR_6_B, CAR_7_B, CAR_8_B, CAR_9_B,
    BUS_11_20, BUS_21_30, BUS_31_40
}
